"""Hof agent: OpenAI tool-calling with mutation confirmation and NDJSON streaming."""

from hof.agent.conversation_state import (
    MAX_CONVERSATION_STATE_BYTES,
    AgentConversationDraftV1,
    AgentConversationPlanV1,
    AgentConversationStateV1,
    conversation_state_json_size,
    enforce_max_conversation_state_bytes,
    normalize_conversation_state_for_storage,
    validate_conversation_state,
)
from hof.agent.extensions import (
    AgentExtension,
    MergedExtensions,
    discover_domain_extensions,
    get_all_extensions,
    merge_extensions,
    register_agent_extension,
)
from hof.agent.plan_types import (
    PlanClarificationAnswer,
    PlanClarificationBarrierV1,
    PlanClarificationOption,
    PlanClarificationQuestion,
    PlanProposal,
    PlanStep,
    parse_plan_proposal,
)
from hof.agent.policy import (
    HOF_BUILTIN_TERMINAL_EXEC,
    AgentPolicy,
    ConfirmationSummaryMode,
    InboxReviewSummaryMode,
    InboxScanAfterInboxResumeFn,
    InboxScanAfterMutationsFn,
    InboxSnapshotFn,
    InboxWatchDescriptor,
    MutationBatchEntry,
    MutationInboxWatchFn,
    MutationPostApplyFn,
    MutationPreviewResult,
    PostApplyReviewHint,
    VerifyInboxWatchFn,
    configure_agent,
    get_agent_policy,
    inbox_watch_from_wire,
    inbox_watch_to_wire,
    mutation_preview_to_wire,
    post_apply_review_hint_to_wire,
    try_get_agent_policy,
)
from hof.agent.sandbox.config import SandboxConfig
from hof.agent.stream import (
    collect_agent_chat_from_stream,
    default_attachments_system_note,
    default_normalize_attachments,
    iter_agent_chat_stream,
    iter_agent_resume_inbox_stream,
    iter_agent_resume_plan_clarification_stream,
    iter_agent_resume_stream,
    iter_agent_resume_web_session_stream,
)
from hof.agent.subagent import iter_subagent_chat_stream
from hof.agent.tooling import format_cli_line

__all__ = [
    "PlanClarificationAnswer",
    "PlanClarificationBarrierV1",
    "PlanClarificationOption",
    "PlanClarificationQuestion",
    "PlanProposal",
    "PlanStep",
    "parse_plan_proposal",
    "MAX_CONVERSATION_STATE_BYTES",
    "AgentConversationDraftV1",
    "AgentConversationPlanV1",
    "AgentConversationStateV1",
    "AgentPolicy",
    "ConfirmationSummaryMode",
    "HOF_BUILTIN_TERMINAL_EXEC",
    "InboxReviewSummaryMode",
    "InboxScanAfterInboxResumeFn",
    "InboxScanAfterMutationsFn",
    "InboxSnapshotFn",
    "InboxWatchDescriptor",
    "MutationBatchEntry",
    "MutationInboxWatchFn",
    "MutationPostApplyFn",
    "MutationPreviewResult",
    "PostApplyReviewHint",
    "SandboxConfig",
    "VerifyInboxWatchFn",
    "inbox_watch_from_wire",
    "inbox_watch_to_wire",
    "mutation_preview_to_wire",
    "post_apply_review_hint_to_wire",
    "collect_agent_chat_from_stream",
    "configure_agent",
    "conversation_state_json_size",
    "default_attachments_system_note",
    "default_normalize_attachments",
    "enforce_max_conversation_state_bytes",
    "format_cli_line",
    "get_agent_policy",
    "iter_agent_chat_stream",
    "iter_agent_resume_inbox_stream",
    "iter_agent_resume_plan_clarification_stream",
    "iter_agent_resume_stream",
    "iter_agent_resume_web_session_stream",
    "iter_subagent_chat_stream",
    "normalize_conversation_state_for_storage",
    "try_get_agent_policy",
    "validate_conversation_state",
    "AgentExtension",
    "MergedExtensions",
    "discover_domain_extensions",
    "get_all_extensions",
    "merge_extensions",
    "register_agent_extension",
]
